//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesDatas.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MesDatas.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品条码.
        /// </summary>
        public static string d2Barcode {
            get {
                return ResourceManager.GetString("d2Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作员.
        /// </summary>
        public static string d2Human {
            get {
                return ResourceManager.GetString("d2Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品型号.
        /// </summary>
        public static string d2Model {
            get {
                return ResourceManager.GetString("d2Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 序号.
        /// </summary>
        public static string d2No {
            get {
                return ResourceManager.GetString("d2No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品结果.
        /// </summary>
        public static string d2Result {
            get {
                return ResourceManager.GetString("d2Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流程.
        /// </summary>
        public static string d2Route {
            get {
                return ResourceManager.GetString("d2Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 过站状态.
        /// </summary>
        public static string d2Status {
            get {
                return ResourceManager.GetString("d2Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时间.
        /// </summary>
        public static string d2Time {
            get {
                return ResourceManager.GetString("d2Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap kaifa {
            get {
                object obj = ResourceManager.GetObject("kaifa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下限.
        /// </summary>
        public static string LowerLimit {
            get {
                return ResourceManager.GetString("LowerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 待机.
        /// </summary>
        public static string standby {
            get {
                return ResourceManager.GetString("standby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结果.
        /// </summary>
        public static string TestResult {
            get {
                return ResourceManager.GetString("TestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上限.
        /// </summary>
        public static string UpperLimit {
            get {
                return ResourceManager.GetString("UpperLimit", resourceCulture);
            }
        }
    }
}
